### ISSUE TITLE
这个工具还更新么

### ISSUE THREAD

**Issue by lonelysoul** [hsernos/Txray#11]
@hsernos 
工具用着不错，还更新吗；

**Comment by hsernos** [comment]
个人自用项目，更新较慢，下个版本预计5.5发布。

**Comment by lonelysoul** [comment]
东西不错，是我除家里之外的场所使用的工具。
感谢作者。赞👍

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: hsernos ***@***.***>
发送时间: Tuesday, April 19, 2022 10:14:06 PM
收件人: hsernos/Txray ***@***.***>
抄送: lonelysoul ***@***.***>; Author ***@***.***>
主题: Re: [hsernos/Txray] 这个工具还更新么 (Issue #11)


个人自用项目，更新较慢，下个版本预计5.5发布。
