### ISSUE TITLE
执行run报错

### ISSUE THREAD

**Issue by xujiaji** [hsernos/Txray#13]
### 版本、系统及CPU架构

1.Txray-linux-64  v3.0.5

2.linux x86-64

### 描述问题
添加节点后，执行run报错

### 复现问题的步骤
run

### Txray设置以及相关截图
<img width="863" alt="image" src="https://user-images.githubusercontent.com/16447251/167143527-ee9169cf-7217-4e38-b1b1-b633d3c59499.png">

<img width="859" alt="image" src="https://user-images.githubusercontent.com/16447251/167141942-85e00a43-494e-4888-827d-cface21194b6.png">

**Comment by hsernos** [comment]
xray没有添加可执行权限，`chmod u+x xray`。

**Comment by xujiaji** [comment]
感谢感谢，可以了。macos上xray没有加权限也运行了。没想到linux上面要加

**Comment by Whichbfj28** [comment]
> chmod u+x xray

确实是权限问题
chmod -R 0777  程序目录
搞定
