### ISSUE TITLE
MacOS stop无法停止进程中的xray, 手动kill后, run失效

### ISSUE THREAD

**Issue by dario-github** [hsernos/Txray#14]
### 版本、系统及CPU架构

1.你在使用什么版本的Txray，例如 ‘Txray-macos-64  v3.0.2’

Txray-macos-64  v3.0.2

2.你所使用的操作系统及CPU架构，例如 ‘windows11  x86-64’

MacOS

### 描述问题

stop后进程依然存在, 必须手动kill, 但手动kill后, 执行run会出现问题, 所有节点都ping不通, 此时必须nohup手动启动xray, 才能继续使用run启动.

### 复现问题的步骤

如上, 依步骤执行即可

### Txray设置以及相关截图
贴入Txray设置（终端运行 Txray setting 查看），以及问题相关的截图。

**Comment by hsernos** [comment]
更新到3.0.6

**Comment by dario-github** [comment]
3.0.6问题依然存在
