### ISSUE TITLE
求大佬更新下能支持macos13吗

### ISSUE THREAD

**Issue by 759071793** [hsernos/Txray#15]
### 版本、系统及CPU架构

1.你在使用什么版本的Txray，例如 ‘Txray-macos-64  v3.0.2’
最新版本

2.你所使用的操作系统及CPU架构，例如 ‘windows11  x86-64’
Macos

### Txray设置以及相关截图
贴入Txray设置（终端运行 Txray setting 查看），以及问题相关的截图。

**Comment by hsernos** [comment]
能描述清楚一点吗？CPU是m1 m2还是其他，你用的是那个架构的txray，请按规范填写。

**Comment by 759071793** [comment]
不好意思哈，我没有描述清楚。
版本、系统及CPU架构

1.你在使用什么版本的Txray
Txray - Xray Shell Client - v3.0.6

2.你所使用的操作系统及CPU架构，例如 ‘windows11 x86-64’
Macbookpro 2018款 intel版本 i7 处理器

描述问题
升级之后就没发使用了，有截图，重新赋予了权限也不行。

Txray设置以及相关截图
<img width="565" alt="截屏2022-06-15 16 50 30" src="https://user-images.githubusercontent.com/23308600/173786442-efcd1fab-9a8f-4a0a-8dad-06ea2a42efc0.png">

贴入Txray设置（终端运行 Txray setting 查看），以及问题相关的截图。
<img width="565" alt="截屏2022-06-15 16 50 30" src="https://user-images.githubusercontent.com/23308600/173786666-b2c26d72-898c-40b3-973f-2b74d979980d.png">

**Comment by 759071793** [comment]
手贱升级到macos13的测试版了。

**Comment by 759071793** [comment]
多运行几遍可以运行，初次运行，会提示上面错误。

另外，而且macos13测试版好像浏览器没法代理，telegram自带的代理可以代理成功，系统代理不行，大家暂时不要尝鲜。。
<img width="615" alt="截屏2022-06-15 16 55 41" src="https://user-images.githubusercontent.com/23308600/173788615-6b026a02-7b50-4708-a022-be437167ed82.png">
系统设置里的代理不起作用，暂时不要升级Macos13测试版

**Comment by hsernos** [comment]
报错好像和 #13 一样

**Comment by hsernos** [comment]
你看看直接运行xray行不行

**Comment by 759071793** [comment]
> 你看看直接运行xray行不行

好的，我没有管那个报错，我继续run几遍又可以用了，尴尬，确定是赋予了u+x权限的
