### ISSUE TITLE
proxyconnect tcp: dial tcp 127.0.0.1:1080: connect: connection refused

### ISSUE THREAD

**Issue by khalitt** [hsernos/Txray#16]
### 版本、系统及CPU架构

1.你在使用什么版本的Txray，例如 ‘Txray-macos-64  v3.0.2’
Txray-linux-64 v3.0.6

2.你所使用的操作系统及CPU架构，例如 ‘windows11  x86-64’
pve 5.15.35 x86-64

### 描述问题

执行run之后启动成功，但是无法成功通过测试，显示proxyconnect tcp: dial tcp 127.0.0.1:1080: connect: connection refused

### 复现问题的步骤

执行run

### Txray设置以及相关截图
贴入Txray设置（终端运行 Txray setting 查看），以及问题相关的截图。

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/20548808/174487420-7624688e-88dc-4931-bcd2-b1db05db60a7.png">
<img width="729" alt="image" src="https://user-images.githubusercontent.com/20548808/174487436-be4bedf5-d93d-4911-8716-b07b156a8308.png">

**Comment by hsernos** [comment]
启动成功只是指节点格式正确，并不代表节点没问题，你得先确定节点是否正常，或者试试改一下端口
