### ISSUE TITLE
能否自定义配置文件和日志的路径

### ISSUE THREAD

**Issue by Whichbfj28** [hsernos/Txray#19]
data.json、routing.json、config.json、info.log、setting.toml、xray_access.log、
现在会产生这几个文件。除了xray_access.log可以自定义配置外。其他的好像无法自定义配置会在程序目录生成。能否手动指定这些文件的目录

**Comment by hsernos** [comment]
配置文件目录优先级: 环境变量 `TXRAY_HOME` > Txray 所在目录

**Comment by Whichbfj28** [comment]
> 配置文件目录优先级: 环境变量 `TXRAY_HOME` > Txray 所在目录

能否进行自定义呢

**Comment by hsernos** [comment]
不支持命令指定，可以配置环境变量指定目录
