### ISSUE TITLE
一个vless节点已经添加，命令run报错

### ISSUE THREAD

**Issue by nctqaq** [hsernos/Txray#2]
https://github.com/XTLS/Xray-core/releases/download/v1.4.5/Xray-freebsd-arm32-v7a.zip
https://github.com/hsernos/Txray/releases/download/v3.0.0/Txray-linux-arm.zip
Hardware:Raspberry 3B
![image](https://user-images.githubusercontent.com/63450987/136677716-78a6dbb4-e7c3-4a49-a074-c7e5d0f1b3e3.png)

`pi@raspberrypi:~/txray $ lsb_release -a`
`No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster`
`Txray - Xray Shell Client - v3.0.0
>>> run
2021-10-10 02:02:36 [error] 开启xray服务失败, 查看下面报错信息来检查出错问题
>>> run
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xacfec]

goroutine 1 [running]:
os.(*Process).signal(0x0, {0x46c974, 0x6200a8})
	/usr/local/go/src/os/exec_unix.go:64 +0x38
os.(*Process).Signal(...)
	/usr/local/go/src/os/exec.go:138
os.(*Process).kill(...)
	/usr/local/go/src/os/exec_posix.go:68
os.(*Process).Kill(...)
	/usr/local/go/src/os/exec.go:123
Txray/xray.Stop()
	/Users/hsernos/code/go/Txray/xray/service.go:121 +0x48
Txray/xray.run({0x46f634, 0x1c96400})
	/Users/hsernos/code/go/Txray/xray/service.go:84 +0x50
Txray/xray.Start({0x3eea11, 0x1})
	/Users/hsernos/code/go/Txray/xray/service.go:30 +0x12c
Txray/cmd.InitServiceShell.func1(0x1e163f0)
	/Users/hsernos/code/go/Txray/cmd/xray.go:19 +0x74
github.com/abiosoft/ishell.(*Shell).handleCommand(0x1e0c000, {0x1e12258, 0x1, 0x1})
	/Users/hsernos/go/pkg/mod/github.com/abiosoft/ishell@v2.0.0+incompatible/ishell.go:250 +0x120
github.com/abiosoft/ishell.handleInput(0x1e0c000, {0x1e12258, 0x1, 0x1})
	/Users/hsernos/go/pkg/mod/github.com/abiosoft/ishell@v2.0.0+incompatible/ishell.go:204 +0x34
github.com/abiosoft/ishell.(*Shell).run(0x1e0c000)
	/Users/hsernos/go/pkg/mod/github.com/abiosoft/ishell@v2.0.0+incompatible/ishell.go:183 +0x318
github.com/abiosoft/ishell.(*Shell).Run(0x1e0c000)
	/Users/hsernos/go/pkg/mod/github.com/abiosoft/ishell@v2.0.0+incompatible/ishell.go:99 +0x28
main.main()
	/Users/hsernos/code/go/Txray/Txray.go:48 +0x258
pi@raspberrypi:~/txray $`

**Comment by hsernos** [comment]
@nctqaq 能否把节点发我测试，私发我邮箱hsernos@163.com。

**Comment by hsernos** [comment]
已解决，不是软件问题。
