### ISSUE TITLE
socks

### ISSUE THREAD

**Issue by FlashIvano** [hsernos/Txray#34]
### 版本、系统及CPU架构

1. Txray-Linux-64  v3.0.7

2.你所使用的操作系统及CPU架构，例如 ‘windows11  x86-64’

Rocky Linux 9

### 描述问题

添加的 socks5 节点后 config.json 里的users对象格式错误

2024-02-22 17:28:06 [error] A unified platform for anti-censorship.
2024-02-22 17:28:06 [error] 2024/02/22 17:28:06 [Info] infra/conf/serial: Reading config: /opt/Txray/config.json
2024-02-22 17:28:06 [error] Failed to start: main: failed to load config files: [/opt/Txray/config.json] > infra/conf: failed to parse to outbound detour config. > json: cannot unmarshal object into Go struct field SocksRemoteConfig.servers.users of type []json.RawMessage

        "outbounds": [
                {
                        "mux": {
                                "enabled": false
                        },
                        "protocol": "socks",
                        "settings": {
                                "servers": [
                                        {
                                                "address": "1.2.3.4",
                                                "port": 1234,
                                                "users": {
                                                        "pass": "passhere",
                                                        "user": "userhere"
                                                }
                                        }
                                ]
                        },
                        "streamSettings": {
                                "network": "tcp",
                                "tcpSettings": {
                                        "header": {
                                                "type": "none"
                                        }
                                }
                        },
                        "tag": "proxy"
                },

### 修正
应该是
                                                "users": [{
                                                        "pass": "passhere",
                                                        "user": "userhere"
                                                }]

**Comment by hsernos** [comment]
已修复，下载更新即可
