### ISSUE TITLE
node add -l  Vmess://xxxxxx 执行后,再执行node -d 发现没有节点

### ISSUE THREAD

**Issue by dcdebug** [hsernos/Txray#7]
### 版本、系统及CPU架构

1.Txray-linux-64.zip

2.Ubuntu 18.04.6 LTS \n \l x86-64

### 描述问题

在 Txray Shell 命令行内执行：
node add -l vmess://xxxx 
### Txray设置以及相关截图
Txray - Xray Shell Client - v3.0.3
>>> setting
+-----------+----------+---------+--------------+--------------------+----------+
| SOCKS端口 | HTTP端口 | UDP转发 | 流量地址监听 | 允许来自局域网连接 | 多路复用 |
+-----------+----------+---------+--------------+--------------------+----------+
|   1080    |    0     |  true   |     true     |       false        |  false   |
+-----------+----------+---------+--------------+--------------------+----------+
+---------+---------+--------------+-----------------+--------------+------------------+
| DNS端口 | 国外DNS |   国内DNS    |   备用国内DNS   |   路由策略   | 绕过局域网和大陆 |
+---------+---------+--------------+-----------------+--------------+------------------+
|  1350   | 1.1.1.1 | 119.29.29.29 | 114.114.114.114 | IPIfNonMatch |       true       |
+---------+---------+--------------+-----------------+--------------+------------------+
+-------------------------+-------------------+------------+
|       测试国外URL       | 测试超时时间 (秒) | 启动时执行 |
+-------------------------+-------------------+------------+
| https://www.youtube.com |         5         |            |
+-------------------------+-------------------+------------+

贴入Txray设置（终端运行 Txray setting 查看），以及问题相关的截图。

结果:
>>> node -d 
+------+------+------+------+------+----------+
| 索引 | 协议 | 别名 | 地址 | 端口 | 测试结果 |
+------+------+------+------+------+----------+
+------+------+------+------+------+----------+
[ 0/0 ] 无节点

**Comment by hsernos** [comment]
@dcdebug 如果方便的话，可以把节点链接发给我吗，直接回复或私发到我邮箱hsernos@163.com

**Comment by dcdebug** [comment]
> hsernos@163.com

已经发送，请注意查收

**Comment by hsernos** [comment]
@dcdebug 
你的链接格式不对，这是标准提案，我是根据这实现的，https://github.com/XTLS/Xray-core/issues/91

**Comment by hsernos** [comment]
将你的格式手动解码成标准格式，测试连接外网成功，已发至你的邮箱。
